version: '2'
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  redis-node-1:
    build:
      context: redis-1
      args:
        PORT: '7000'
    hostname: server
    ports:
      - '7000:7000'
    networks:
      frontend:
        ipv4_address: 172.20.0.2
  redis-node-2:
    build:
      context: redis-2
      args:
        PORT: '7001'
    hostname: server
    ports:
      - '7001:7000'
    networks:
      frontend:
        ipv4_address: 172.20.0.3
  redis-node-3:
    build:
      context: redis-3
      args:
        PORT: '7002'
    hostname: server
    ports:
      - '7002:7000'
    networks:
      frontend:
        ipv4_address: 172.20.0.4
  redis-node-4:
    build:
      context: redis-4
      args:
        PORT: '7003'
    hostname: server
    ports:
      - '7003:7000'
    networks:
      frontend:
        ipv4_address: 172.20.0.5
  redis-node-5:
    build:
      context: redis-5
      args:
        PORT: '7004'
    hostname: server
    ports:
      - '7004:7000'
    networks:
      frontend:
        ipv4_address: 172.20.0.6
  redis-node-6:
    build:
      context: redis-6
      args:
        PORT: '7005'
    hostname: server
    ports:
      - '7005:7000'
    networks:
      frontend:
        ipv4_address: 172.20.0.7
